config/routes.rb
BoardManager::Application.routes.draw do
  devise_for :users, :path_prefix => 'auth'

  resource :knighttable, only: :show
  resources :boardchecks
  resources :boards
  resources :computers
  resources :projectors

  resources :quests do
    post :accept, on: :member
  end
  
  resources :rooms do
    get :info, on: :member
  end
  
  resources :users do
    resources :duties, only: :index do
      get :edit_all, on: :collection
      post :update_all, on: :collection
    end
    
    post :tweet, on: :member
  end

  get "qrcode" => "qrcodes#show"
  root :to => 'knighttables#show'
end

app/models/duty.rb
class Duty < ActiveRecord::Base
  belongs_to :user
  belongs_to :period

  attr_accessible :user_id, :period_id, :room

  validates :user_id, :presence => true
  validates :period_id, :presence => true, :uniqueness => { scope: :user_id }
  validates :room, :presence => true
  
  scope :ordered, includes(:period, :user).order( "periods.day, periods.number, users.level DESC" )
end

app/controllers/duties_controller.rb
class DutiesController < ApplicationController
  filter_resource_access :nested_in => :user, attribute_check: true, collection: [:index, :edit_all, :update_all]
  
  def index
    load_duties
  end

  def edit_all
    load_duties
  end

  def update_all
    @user = User.find params[:user_id]
    @user.duties.destroy_all
    periods = Period.all
    
    params[:duties].each_pair do |lesson, room|
      no, day = lesson.split('|')
      period  = periods.find { |p| p.day == day.to_i && p.number == no.to_i }
      room    = room.strip.sub( /^(?=\d)/, "R")
      @user.duties.create period_id: period.id, room: room
    end
    
    redirect_to user_duties_path(@user)
  end
  
  protected
    def load_duties
      @user = User.includes(:duties).find params[:user_id]
      @timetable = Array.new( 8 ) { Array.new(6, nil) }
      @duties = @user.duties.ordered
      @duties.each { |d| @timetable[ d.period.number ][ d.period.day ] = d.room }

      @timetable_stats = Array.new( 8 ) { Array.new(6, 0) }
      Duty.all.each { |d| @timetable_stats[ d.period.number ][ d.period.day ] += 1 }
    end

    def set_active_item
      @active = current_user.id == params[:user_id].to_i ? :user : :users
    end
end

app/helpers/duties_helper.rb
module DutiesHelper
end

app/views/duties/_form.html.haml
= simple_form_for @duty, :html => { :class => 'form-horizontal' } do |f|
  = f.input :user_id
  = f.input :period_id
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), duties_path, :class => 'btn'

app/views/duties/_list.html.haml
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Tag
      %th Stunde
      %th Raum
  %tbody
    - duties.each do |duty|
      %tr
        %td= format_day duty.period.day
        %td= duty.period.number_human
        %td= duty.room

app/views/duties/_table.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th.span1 Stunde
      - 1.upto(5) do |day|
        %th.span2.center= format_day day
  %tbody
    - timetable.each_with_index do |row, no|
      %tr
        %th.right #{no + 1}.
        - 1.upto(5) do |day|
          %td.span2.center 
            = row[day]

app/views/duties/edit_all.html.haml
- model_class = Duty

.page-header
  %h1 #{@user.firstname}: Bereitschaften bearbeiten

= form_tag "update_all" do
  %table.table.table-bordered
    %thead
      %tr
        %th Stunde
        - 1.upto(5) do |day|
          %th.center= format_day day
    %tbody
      - (0..7).each do |p|
        %tr
          %th.right #{p + 1}.
          - 1.upto(5) do |day|
            %td.center{ class: format_duty_class( @timetable_stats[p][day] ) }
              = text_field_tag "[duties]#{p}|#{day}", @timetable[p][day], maxlength: 12, :class => "span2"
  = link_to t('helpers.links.back'), :back, :class => 'btn'
  = submit_tag "Speichern", :class => 'btn btn-primary'


%h3 Legende
%table.table.table-bordered
  %tbody
    %tr
      %td.center.fail keine Bereitschaften
      %td.center.warn nur 1 oder 2 Bereitschaften
      %td.center.ok genügend Bereitschaften

app/views/duties/index.html.haml
.page-header
  %h1 #{@user.titled}: #{@duties.count} Bereitschaften

= render partial: 'duties/table', locals: { timetable: @timetable }

= link_to "Zurück", user_path(@user), :class => 'btn'
= link_to "Bereitschaften bearbeiten", edit_all_user_duties_path(@user), :class => 'btn'

app/views/duties/new.html.haml
- model_class = Duty
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/duties/show.html.haml
- model_class = Duty
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @duty.user_id
%p
  %strong= model_class.human_attribute_name(:period_id) + ':'
  %br
  = @duty.period_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), duties_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_duty_path(@duty), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), duty_path(@duty), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'