config/routes.rb
BoardManager::Application.routes.draw do
  devise_for :users, :path_prefix => 'auth'

  resource :knighttable, only: :show
  resources :boardchecks
  resources :boards
  resources :computers
  resources :projectors

  resources :quests do
    post :accept, on: :member
  end
  
  resources :rooms do
    get :info, on: :member
  end
  
  resources :users do
    resources :duties, only: :index do
      get :edit_all, on: :collection
      post :update_all, on: :collection
    end
    
    post :tweet, on: :member
  end

  get "qrcode" => "qrcodes#show"
  root :to => 'knighttables#show'
end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base
  CHARACTERS = ('A'..'Z').to_a + ('a'..'z').to_a + ('0'..'9').to_a
  LEVELS     = ["Knappe", "Ritter", "Fürst", "Herzog", "König"]
  MAX_LEVEL  = LEVELS.size - 1
  
  def self.create_password
    Array.new(8) { CHARACTERS.sample }.join
  end
  
  # Include default devise modules. Others available are: :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :confirmable, :lockable, :timeoutable

  has_many :boardchecks, dependent: :nullify
  has_many :duties, dependent: :destroy
  has_many :quests, dependent: :destroy
  has_many :sponsorships, dependent: :destroy
  has_many :rooms, :through => :sponsorships
  has_many :open_quests, :through => :rooms, :source => :quests
  
  scope :ordered, order(:year, :form, :lastname, :firstname)
  scope :admins, where(level: MAX_LEVEL)
  scope :twitterers, where("twitter_name <> ''")
  scope :by_level, order("level desc")
  
  # Setup accessible (or protected) attributes for your model
  accepts_nested_attributes_for :sponsorships, :reject_if => lambda { |a| a[:room_id].blank? }, :allow_destroy => true
  attr_accessible :firstname, :lastname, :year, :form, :email, :twitter_name, :password,
    :password_confirmation, :remember_me
  attr_accessible :firstname, :lastname, :year, :form, :email, :twitter_name, :password,
    :password_confirmation, :remember_me, :level, :sponsorships_attributes, :room_ids, as: :admin

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true
  
  def yearform
    year.present? ? "#{year}#{form}" : '-'
  end

  def level_s
    LEVELS[level]
  end
    
  def role_symbols
    [ level_s.parameterize.underscore.to_sym ]
  end
  
  def titled
    "#{level_s} #{firstname} (#{yearform})"
  end
  
  def name
    titled
  end
  
  def twitters?
    twitter_name.present?
  end
end

app/controllers/users_controller.rb
# encoding: UTF-8
class UsersController < InheritedResources::Base
  filter_access_to :all
  filter_access_to :create, attribute_check: false

  def show
    @rooms  = resource.rooms.ordered
    @quests = resource.quests.ordered
    @quests += resource.open_quests.ordered

    load_duties
  end
  
  def create
    @user = User.new
    @user.assign_attributes( params[:user], :as => as_role[:as] )
    @user.password = @user.password_confirmation = User.create_password
    create!
  end

  def edit
    resource.sponsorships.build
  end
  

  def update
    @user = User.find params[:id]
    @user.assign_attributes( params[:user], :as => as_role[:as] )
    if @user.level_changed? && @user.level > @user.level_was
      UserMailer.level_upgraded(@user, @user.level_was).deliver
    end

    update!
  end

  def tweet
    @user   = User.find params[:id]
    twitter = @user.twitter_name
    message = "MSO Tafelrunde Testtweet #{l Time.now}"

    begin
      if Rails.env.production?
        Twitter.direct_message_create( twitter, message )
      else
        # Hack to avoid Twitter timestamp problems
        Timecop.return 
        Twitter.direct_message_create( twitter, message )
        Timecop.travel( Time.parse( BoardManager::Config.time ) )
      end
      
      flash[:notice] = "Erfolgreich an #{twitter} gezwitschert!"
    rescue Exception => e
      flash[:error] = "Beim Zwitschern an ‘#{twitter}’ ist etwas schief gegangen. Stelle sicher, dass ‘#{twitter}’ ‘#{ BoardManager::Config.twitter['name'] }’ folgt.<br>Ursprüngliche Fehlermeldung: “#{e.message}”".html_safe
    end

    redirect_to :back
  end
  
  protected
    def collection
      @users ||= end_of_association_chain.includes(:duties).ordered
    end

    def role_given?
      permitted_to?(:update, :users)
    end
        
    def as_role
      { as: permitted_to?(:update, :users) ? :admin : :default }
    end

    def set_active_item
      @active = (current_user && current_user.id == params[:user_id].to_i) ? :user : :users
    end

    def load_duties
      @timetable = Array.new( 8 ) { Array.new(6, nil) }
      @duties = @user.duties.ordered
      @duties.each { |d| @timetable[ d.period.number ][ d.period.day ] = d.room }
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def format_name(user)
    s = "#{user.firstname} #{user.lastname}"
    s += " (#{user.yearform})" if user.year.present?
    return s
  end

  def format_title_name(user)
    "#{user.level_s} #{format_name(user)}"
  end
end

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  = f.input :firstname
  = f.input :lastname
  = f.input :email
  = f.input :twitter_name
  = f.input :year, collection: 5..12
  = f.input :form, collection: 'a'..'e'
  = f.input :level, collection: array_to_hash(User::LEVELS), include_blank: false
  = f.association :rooms, collection: Room.ordered

  -# = f.simple_fields_for :sponsorships do |builder|
  -#   = builder.association :room, label: 'Burg'
  -#   = builder.input :user_id, as: :hidden

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.haml
.page-header
  %h1 Tafelritter bearbeiten

= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1
    %i.icon-group
    Tafelritter

%p
  Aktuell gibt es an der Marienschule Opladen 
  %b #{@users.count} ausgebildete Tafelritter.

%table.table.table-striped
  %thead
    %tr
      %th Nr.
      %th= model_class.human_attribute_name(:yearform)
      %th= model_class.human_attribute_name(:firstname)
      - if permitted_to? :read, @users.first
        %th= model_class.human_attribute_name(:lastname)
      -# %th Ritterschlag
      %th Bereitschaft
      - if permitted_to? :read, :users
        %th Burg
        %th Prüfungen
        %th Gesuche
        %th Login
      - if permitted_to? :edit, :users
        %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each_with_index do |user, i|
      %tr{ class: user == current_user && 'success' }
        %td.right= i + 1
        %td= user.yearform
        %td
          %b= user.firstname
        - if permitted_to? :read, user
          %td= user.lastname
        -# %td=format_date user.created_at
        %td.right
          - if user.twitter_name.present?
            %i.icon-twitter.icon-white
          = format_number user.duties.count
        - if permitted_to? :show, user
          %td= user.rooms.ordered.map(&:name).join(', ')
          %td.right= format_number user.boardchecks.count
          %td.center #{format_number user.quests.solved.count} / #{format_number user.quests.count}
          %td=format_date user.last_sign_in_at, :short
        - if permitted_to? :edit, user
          %td
            .btn-group
              %a.btn.btn-primary.btn-small{ href: user_path(user) }
                %i.icon-user.icon-white= " #{user.level_s}"
              - if permitted_to? :edit, user
                %a.btn.btn-primary.btn-small.dropdown-toggle( data-toggle='dropdown' )
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to "<i class='icon-envelope'></i> E-Mail".html_safe, format_email(user)
                  - if user.twitters?
                    %li= link_to "<i class='icon-twitter'></i> Test-Tweet".html_safe, tweet_user_path(user), method: :post
                  %li= link_to "<i class='icon-calendar'></i> Bereitschaften".html_safe, edit_all_user_duties_path(user)
                  %li= link_to "<i class='icon-pencil'></i> Einstellungen".html_safe, edit_user_path(user)
                  %li= link_to "<i class='icon-trash'></i> Löschen".html_safe, user_path(user), data: { method: :delete, confirm: 'Seid Ihr Euch sicher?' }

- if permitted_to?(:create, User.new)
  %p= link_to 'Neuer Tafelritter', new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1 Neuen Tafelritter anlegen

= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1 #{@user.level_s} #{@user.firstname}

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to 'Bereitschaften bearbeiten', edit_all_user_duties_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'


%h2 Hilfegesuche
- if @quests.present?
  = render partial: 'quests/table', locals: { quests: @quests }

%h2 Tafelchecks: #{@user.boardchecks.count}
- if @user.boardchecks.present?
  = render partial: 'boardchecks/table', locals: { boardchecks: @user.boardchecks.ordered }


%h2 Burgen
- if @rooms.any?
  = render partial: 'rooms/table', locals: { rooms: @rooms }
- else
  %p Du hast noch keine Burg zugewiesen bekommen.


%h2 #{Duty.model_name.human( count: @duties.count )}: #{@duties.count}
- if @timetable.present?
  = render partial: 'duties/table', locals: { timetable: @timetable }


%h2 Persönliche Daten
%table.table.table-striped
  %tr
    %th Name
    %td #{@user.firstname} #{@user.lastname}
  %tr
    %th E-Mail
    %td= link_to @user.email, format_email(@user)
  %tr
    %th Twitter
    %td= format_twitter(@user.twitter_name)
  %tr
    %th Rang
    %td= @user.level_s
  %tr
    %th Klasse/Stufe
    %td= @user.yearform
  %tr
    %th Bestätigt?
    %td= format_tick @user.confirmed?
  %tr
    %th Entsperrt?
    %td= format_tick !@user.access_locked?
  %tr
    %th Letzter Login
    %td= l @user.current_sign_in_at rescue '-'