config/routes.rb
BoardManager::Application.routes.draw do
  devise_for :users, :path_prefix => 'auth'

  resource :knighttable, only: :show
  resources :boardchecks
  resources :boards
  resources :computers
  resources :projectors

  resources :quests do
    post :accept, on: :member
  end
  
  resources :rooms do
    get :info, on: :member
  end
  
  resources :users do
    resources :duties, only: :index do
      get :edit_all, on: :collection
      post :update_all, on: :collection
    end
    
    post :tweet, on: :member
  end

  get "qrcode" => "qrcodes#show"
  root :to => 'knighttables#show'
end

app/models/room.rb
class Room < ActiveRecord::Base
  BUILDINGS        = { 0 => 'Altbau', 1 => 'Neubau' }
  LEVELS           = { 0 => 'Erdgeschoss', 1 => '1. Stock', 2 => '2. Stock', 3 => '3. Stock' }
  MAX_PENALTY      = 2000
  BUILDING_PENALTY = 150
  LEVEL_PENALTY    = 300

  has_one :computer, dependent: :nullify
  has_one :board, dependent: :nullify
  has_one :projector, dependent: :nullify
  has_many :boardchecks, dependent: :destroy
  has_many :quests, dependent: :destroy
  has_many :sponsorships, dependent: :destroy
  has_many :users, :through => :sponsorships
  
  accepts_nested_attributes_for :computer, :allow_destroy => true
  accepts_nested_attributes_for :board, :allow_destroy => true
  accepts_nested_attributes_for :projector, :allow_destroy => true
  
  validates :building, :presence => true
  validates :level, :presence => true
  validates :name, :presence => true, :uniqueness => true
  
  attr_accessible :building, :level, :name, :computer_attributes, :board_attributes, :projector_attributes
  
  scope :ordered, order(:building, :level, :name)

  def self.named(name)
    Room.where( 'name like ?', "%#{name[/\d+$/]}%").first rescue nil
  end
  
  def building_s
    BUILDINGS[ building ]
  end
  
  def level_s
    LEVELS[ level ]
  end
  
  def last_check_ok?
    check = boardchecks.latest
    return nil unless check.present? 
    return ! check.issues_present?
  end
  
  def number
    name[ /\d+$/ ].to_i
  end
  
  def distance(other)
    Room.distance( self.name, other.is_a?(Room) ? other.name : other )
  end
  
  protected
    def self.distance(r1, r2)
      r1 = Room.room_by_name(r1)
      r2 = Room.room_by_name(r2)
      return MAX_PENALTY if r1.building == 2 || r1.building == 2
      
      penalty = 0
      penalty += BUILDING_PENALTY if r1.building != r2.building
      penalty += LEVEL_PENALTY * (r1.level - r2.level).abs
      penalty += (r1.number % 100 - r2.number % 100).abs ** 2
      
      return penalty
    end
    
    def self.room_by_name(name)
      room = Room.new( name: name)
      if (number = name[ /\d+$/ ].to_i) > 0
        room.building = number / 400
        room.level    = number % 400 / 100
      else
        room.building = 2
        room.level    = 4
      end
      
      return room
    end
end

app/controllers/rooms_controller.rb
class RoomsController < InheritedResources::Base
  filter_resource_access
  custom_actions :resource => :info
  layout 'print', only: :info
  
  def show
    @room        = Room.includes(:computer, :board, :projector).find( params[:id] )
    @boardchecks = @room.boardchecks.ordered
    @computer    = @room.computer
    @board       = @room.board
    @projector   = @room.projector
    
    show!
  end

  def info
    @url = new_quest_url( room: resource.name, host: BoardManager::Config.host )
    
    info!
  end

  def edit
    @room = Room.includes(:computer, :board, :projector).find( params[:id] )
    @room.build_computer unless @room.computer.present?
    @room.build_board unless @room.board.present?
    @room.build_projector unless @room.projector.present?
    
    edit!
  end
  
  protected
    def collection
      @rooms ||= end_of_association_chain.ordered
    end

    def set_active_item
      @active = :rooms
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.haml
= simple_form_for @room, :html => { :class => 'form-horizontal' } do |f|
  = f.error_messages
  %fieldset
    %legend Raum
    = f.input :building, collection: Room::BUILDINGS.map {|k, v| [v, k] }
    = f.input :level, collection: Room::LEVELS.map { |k,v| [v, k] }
    = f.input :name

  %fieldset
    %legend Computer
    = f.simple_fields_for :computer do |c|
      = c.input :model
      = c.input :kind
      = c.input :serial
      = c.input :ip
      = c.input :mac_en_address
      = c.input :mac_wifi_address
      = c.input :note, :input_html => { class: 'span5', :rows => 5 }
      = c.input :purchased_on, discard_day: true
      = c.input :_destroy, as: :boolean, label: 'Computer löschen'

  %fieldset
    %legend ActivBoard
    = f.simple_fields_for :board do |b|
      = b.input :manufacturer
      = b.input :model
      = b.input :serial
      = b.input :firmware
      = b.input :note, :input_html => { class: 'span5', :rows => 5 }
      = b.input :purchased_on, discard_day: true
      = b.input :_destroy, as: :boolean, label: 'Tafel löschen'

  %fieldset
    %legend Beamer
    = f.simple_fields_for :projector, @room.projector do |p|
      = p.input :manufacturer
      = p.input :model
      = p.input :serial
      = p.input :resolution, hint: "Format 1600x1200"
      = p.input :_destroy, as: :boolean, label: 'Beamer löschen'

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), rooms_path, :class => 'btn'

app/views/rooms/_qrcode.html.haml
%h2 Raum #{@room.name}

= image_tag qrcode_url(format: 'svg', url: @url)

app/views/rooms/_table.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Nr.
      %th Name
      %th Ort
      %th Ausstattung
      %th Vogt
      %th Prüfungen / Letzte
      - if permitted_to? :read, :rooms
        %th Gesuche
        %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - rooms.each_with_index do |room, i|
      %tr{ class: format_boardcheck_class(room) }
        %td.right= i + 1
        %td
          %b= room.name
        %td #{room.building_s}, #{room.level_s}
        %td
          = room.computer.present? ? "<i class='icon-desktop'></i> ".html_safe : ''
          = room.board.present? ? "<i class='icon-picture'></i> ".html_safe : ''
          = room.projector.present? ? "<i class='icon-lightbulb'></i> ".html_safe : ''
        %td= room.users.map(&:firstname).join(', ')
        %td.center
          = room.boardchecks.count
          \/
          = l room.boardchecks.latest.created_at.to_date, format: :short rescue '-'
        - if permitted_to? :read, room
          %td.right= room.quests.count
          %td
            .btn-group
              %a.btn.btn-primary.btn-small{ href: room_path(room) }
                %i.icon-home.icon-white= " Details"
              - if permitted_to?(:create, :boardchecks) or permitted_to?(:edit, room)
                %a.btn.btn-primary.btn-small.dropdown-toggle( data-toggle='dropdown' )
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to "<i class='icon-check'></i> Neuer Tafelcheck".html_safe, new_boardcheck_path(room_id: room.id)
                  %li= link_to "<i class='icon-qrcode'></i> Code drucken".html_safe, info_room_path(room)
                  %li= link_to "<i class='icon-calendar'></i> Tafelritterplan".html_safe, knighttable_path(roomname: room.name)
                  - if permitted_to?(:edit, room)
                    %li= link_to "<i class='icon-edit'></i> Bearbeiten".html_safe, edit_room_path(room)
                  - if permitted_to?(:destroy, room)
                    %li= link_to "<i class='icon-trash'></i> Löschen".html_safe, room_path(room), data: { method: :delete, confirm: 'Seid Ihr sicher?' }

app/views/rooms/edit.html.haml
- model_class = Room
.page-header
  %h1 Raum bearbeiten

= render :partial => "form"

app/views/rooms/index.html.haml
- model_class = Room
.page-header
  %h1
    %i.icon-home
    Räume

= render partial: 'table', locals: { rooms: @rooms }

- if permitted_to? :create, Room.new
  = link_to "Raum erstellen", new_room_path, :class => 'btn btn-primary'

app/views/rooms/info.html.haml
%h2 Raum #{@room.name}

= image_tag qrcode_url(format: 'svg', url: @url)

%p.small= @url.sub('http://', '')

app/views/rooms/new.html.haml
- model_class = Room
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'Neuer %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/rooms/show.html.haml
- model_class = Room
.page-header
  %h1
    %i.icon-home
    Raum #{@room.name}
    %small #{@room.building_s}, #{@room.level_s}

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), rooms_path, :class => 'btn'
  - if permitted_to? :create, @room.boardchecks.build
    = link_to 'Neuer Tafelcheck', new_boardcheck_path, :class => 'btn btn-primary'
  - if permitted_to? :edit, @room
    = link_to 'Raum bearbeiten', edit_room_path(@room), :class => 'btn'
    = link_to 'Raum löschen', room_path(@room), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

%h2
  %i.icon-check
  Boardchecks
- unless @boardchecks.present?
  Noch keine Überprüfungen durchgeführt.
- else
  = render partial: 'boardchecks/table', locals: { boardchecks: @boardchecks }
%hr


%h2 
  %i.icon-desktop
  Computer

- unless @computer.present?
  Kein Computer.
  -# = link_to "Computer eintragen…", new_computer_path( @room.build_computer )
- else
  = render @computer
%hr


%h2
  %i.icon-picture
  ActivBoard

- unless @board.present?
  Kein ActivBoard.
  -# = link_to "ActivBoard eintragen…", new_board_path( @room.build_board )
- else
  = render @board
%hr

%h2
  %i.icon-lightbulb
  Beamer

- unless @projector.present?
  Kein Beamer.
  -# = link_to "Beamer eintragen…", new_projector_path( @room.build_projector )
- else
  = render @projector
%hr