config/routes.rb
BoardManager::Application.routes.draw do
  devise_for :users, :path_prefix => 'auth'

  resource :knighttable, only: :show
  resources :boardchecks
  resources :boards
  resources :computers
  resources :projectors

  resources :quests do
    post :accept, on: :member
  end
  
  resources :rooms do
    get :info, on: :member
  end
  
  resources :users do
    resources :duties, only: :index do
      get :edit_all, on: :collection
      post :update_all, on: :collection
    end
    
    post :tweet, on: :member
  end

  get "qrcode" => "qrcodes#show"
  root :to => 'knighttables#show'
end

app/views/layouts/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{ href: root_url }= Rails.env.development? ? "DEV Tafelrunde" : "Tafelrunde"
      %ul.nav.pull-right
        - if signed_in?
          %li.dropdown{ class: @active == :user && 'active' }
            %a.dropdown-toggle(data-toggle='dropdown' href='#')
              %i.icon-user
              = current_user.level_s
              = current_user.firstname
              %span.caret
            %ul.dropdown-menu
              %li= link_to "<i class='icon-calendar'></i> Bereitschaften".html_safe, user_duties_path(current_user)
              - if current_user.twitters?
                %li= link_to "<i class='icon-twitter'></i> Test-Tweet".html_safe, tweet_user_path(current_user), method: :post
              %li= link_to "<i class='icon-pencil'></i> Einstellungen".html_safe, edit_user_registration_path
              %li= link_to "<i class='icon-signout'></i> Abmelden!".html_safe, destroy_user_session_path, method: :delete
        - else
          %li.inverse= link_to "<i class='icon-signin'></i> Anmelden".html_safe, new_user_session_path
      .container.nav-collapse
        %ul.nav
          %li{ class: @active == :users && 'active' }= link_to "Ritter", users_path
          %li{ class: @active == :table && 'active' }= link_to "Plan", knighttable_path
          %li{ class: @active == :rooms && 'active' }= link_to "Räume", rooms_path
          - if signed_in?
            %li{ class: @active == :quests && 'active' }= link_to "Gesuche", quests_path
          - else
            %li= link_to "Hilfe!", new_quest_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="de")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "#{'DEV ' if Rails.env.development? }MSO Tafelrunde"
    = csrf_meta_tags
    = stylesheet_link_tag "application#{'_development' if Rails.env.development?}", :media => 'all'
    = stylesheet_link_tag 'print', :media => 'print'
    = favicon_link_tag 'favicon.ico'
    = favicon_link_tag 'apple-touch-icon.png', rel: "apple-touch-icon", sizes: "57x57", type: nil
    = favicon_link_tag 'apple-touch-icon-72x72.png', rel: "apple-touch-icon", sizes: "72x72", type: nil
    = favicon_link_tag 'apple-touch-icon-114x114.png', rel: "apple-touch-icon", sizes: "114x114", type: nil
    = favicon_link_tag 'apple-touch-icon-144x144.png', rel: "apple-touch-icon", sizes: "144x144", type: nil

  %body
    = render 'layouts/navbar'

    .container
      .row
        .span12
          = bootstrap_flash
          = yield
      - if signed_in?
        .footer.inline-list
          %ul
            %li= link_to "Tafelritter", users_path
            %li= link_to "Ritterplan", knighttable_path
            %li= link_to "Räume", rooms_path
            %li= link_to "Tafelchecks", boardchecks_path
            %li= link_to "Hilfegesuche", quests_path
            %li= link_to "Computer", computers_path
            %li= link_to "Tafeln", boards_path
            %li= link_to "Beamer", projectors_path
            %li
              %span.copyright
                &copy; 1866-2013 M. Kühnert,
                = link_to "Marienschule Opladen", 'http://marienschule.com', target: :new

    = javascript_include_tag "application"

app/views/layouts/minimal.html.haml
!!! 5
%html(lang="de")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "#{'DEV ' if Rails.env.development? }MSO BoardManager"
    = csrf_meta_tags
    = stylesheet_link_tag "application#{'_development' if Rails.env.development?}", :media => "all"
    = favicon_link_tag 'favicon.ico'
    = favicon_link_tag 'apple-touch-icon.png', rel: "apple-touch-icon", sizes: "57x57", type: nil
    = favicon_link_tag 'apple-touch-icon-72x72.png', rel: "apple-touch-icon", sizes: "72x72", type: nil
    = favicon_link_tag 'apple-touch-icon-114x114.png', rel: "apple-touch-icon", sizes: "114x114", type: nil
    = favicon_link_tag 'apple-touch-icon-144x144.png', rel: "apple-touch-icon", sizes: "144x144", type: nil

  %body
    .container
      .row
        .span8.offset2
          = bootstrap_flash
          = yield

    = javascript_include_tag "application"

app/views/layouts/print.html.haml
!!! 5
%html(lang="de")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "#{'DEV ' if Rails.env.development? }MSO BoardManager"
    = csrf_meta_tags
    = stylesheet_link_tag "application#{'_development' if Rails.env.development?}", :media => "all"

  %body
    .container
      = yield